# agents/github/agent.py
from typing import TypedDict, List, Optional
from langgraph.graph import StateGraph, START, END
from state import AgentState, Fix, ValidationResult
import agents.github.tools as tools


class GitHubState(TypedDict):
    project_key: str
    branch: str
    fixes: List[Fix]
    validation_result: ValidationResult
    branch_name: str
    pr_url: str


def _build_pr_body(fixes: List[Fix], vr: ValidationResult) -> str:
    rows = "\n".join(
        f"| {f['issue_key']} | `{f['file_path'].split('/')[-1]}` | — |"
        for f in fixes
    )
    resolved_count = len(vr["resolved_issues"])
    remaining_count = len(vr["remaining_issues"])
    scan_line = (
        f"✅ Re-scan passed: {resolved_count} resolved, 0 remaining"
        if vr["all_resolved"]
        else f"⚠️ Re-scan: {resolved_count} resolved, {remaining_count} remaining (max rounds reached)"
    )
    return (
        f"## Auto-fix: SonarQube Issues\n\n"
        f"### Issues Fixed\n"
        f"| Issue Key | File | Rule |\n"
        f"|-----------|------|------|\n"
        f"{rows}\n\n"
        f"### Validation\n"
        f"{scan_line} after round {vr['round_number']}\n\n"
        f"---\n*Generated by auto-sonarqube-reports-fix agent*"
    )


def create_branch_node(state: GitHubState) -> dict:
    branch_name = tools.create_branch(state["project_key"])
    return {"branch_name": branch_name}


def commit_files_node(state: GitHubState) -> dict:
    unique_files = list({f["file_path"] for f in state["fixes"]})
    rule_id = state["fixes"][0]["issue_key"] if state["fixes"] else "sonarqube"
    tools.commit_files(unique_files, rule_id, f"resolve {len(state['fixes'])} SonarQube issues")
    return {}


def create_pr_node(state: GitHubState) -> dict:
    tools.push_branch(state["branch_name"])
    pr_body = _build_pr_body(state["fixes"], state["validation_result"])
    url = tools.create_pr(
        branch_name=state["branch_name"],
        base_branch=state["branch"],
        pr_body=pr_body,
        n_fixed=len(state["fixes"]),
        n_rounds=state["validation_result"]["round_number"],
    )
    return {"pr_url": url}


def _build_graph():
    builder = StateGraph(GitHubState)
    builder.add_node("create_branch", create_branch_node)
    builder.add_node("commit_files", commit_files_node)
    builder.add_node("create_pr", create_pr_node)
    builder.add_edge(START, "create_branch")
    builder.add_edge("create_branch", "commit_files")
    builder.add_edge("commit_files", "create_pr")
    builder.add_edge("create_pr", END)
    return builder.compile()


_graph = _build_graph()


def github_node(state: AgentState) -> dict:
    result = _graph.invoke({
        "project_key": state["project_key"],
        "branch": state["branch"],
        "fixes": state["fixes"],
        "validation_result": state["validation_result"],
        "branch_name": "",
        "pr_url": "",
    })
    return {"pr_url": result["pr_url"]}
